### ISSUE TITLE
branch guide

### ISSUE THREAD

**Issue by kim95175** [kim95175/capstone1#1]
먼저 master 브랜치를 기본으로 가집니다.

각자 작업하시는 내용은 [각자 브랜치명] 으로 만들어서 작업해주시고, 작업이 완료되면 aster에 pull request 남겨주시면 됩니다.

## 자신의 새로운 branch 만드는 방법

- master branch에서 (혹은 분기를 나눌 branch에서) 준비합니다.
- git checkout -b [branch_name] 으로 브랜치를 생성하고 이동합니다. ([branch_name]을 원하는 것으로 바꿉니다.)
- git push -u origin [branch_name] 으로 remote에 자신의 브랜치를 추가해줍니다.

이후 개인 브랜치에서 작업 진행하시면 됩니다.

개인 브랜치에서 작업시에도 병합 문제 발생 예방을 위해 가급적이면 개인 폴더를 만들어 거기에 파일을 백업해주세요!

**Comment by kim95175** [comment]
# branch 작업 후 Pull Request 날리는 과정

- 코드 작업시 각 작업이 자신의 브랜치에서 진행되고 있는지 꼭 확인합니다.

## 작업한 code remote(깃헙)내에 push 하기
-  git add -A    
-  git commit -m "변경 내용"
- git push origin [branch_name]

여기 까지 진행할 시 자신의 branch에 변동사항이 remote에 저장됩니다.

## Pull Request  하는 법
- 이후 깃헙리포로 들어가 Pull requests 탭 클릭
- New pull request
- base: master <- compare :[branch_name] 선택
- create pull request
- 오른쪽 assignee, reviewer, Labels 등 설정
, comment로 추가된 내용 간단히 입력
- Create Pull Request

확인 후 pull request가 merge되면 변동 사항이 master branch에 추가됩니다.

**Comment by bellahj0323** [comment]
> 먼저 master 브랜치를 기본으로 가집니다.
> 
> 각자 작업하시는 내용은 [각자 브랜치명] 으로 만들어서 작업해주시고, 작업이 완료되면 aster에 pull request 남겨주시면 됩니다.
> 
> ## 자신의 새로운 branch 만드는 방법
> * master branch에서 (혹은 분기를 나눌 branch에서) 준비합니다.
> * git checkout -b [branch_name] 으로 브랜치를 생성하고 이동합니다. ([branch_name]을 원하는 것으로 바꿉니다.)
> * git push -u origin [branch_name] 으로 remote에 자신의 브랜치를 추가해줍니다.
> 
> 이후 개인 브랜치에서 작업 진행하시면 됩니다.
> 
> 개인 브랜치에서 작업시에도 병합 문제 발생 예방을 위해 가급적이면 개인 폴더를 만들어 거기에 파일을 백업해주세요!



> 먼저 master 브랜치를 기본으로 가집니다.
> 
> 각자 작업하시는 내용은 [각자 브랜치명] 으로 만들어서 작업해주시고, 작업이 완료되면 aster에 pull request 남겨주시면 됩니다.
> 
> ## 자신의 새로운 branch 만드는 방법
> * master branch에서 (혹은 분기를 나눌 branch에서) 준비합니다.
> * git checkout -b [branch_name] 으로 브랜치를 생성하고 이동합니다. ([branch_name]을 원하는 것으로 바꿉니다.)
> * git push -u origin [branch_name] 으로 remote에 자신의 브랜치를 추가해줍니다.
> 
> 이후 개인 브랜치에서 작업 진행하시면 됩니다.
> 
> 개인 브랜치에서 작업시에도 병합 문제 발생 예방을 위해 가급적이면 개인 폴더를 만들어 거기에 파일을 백업해주세요!

**Comment by bellahj0323** [comment]
+) branch 생성하고 push 할 때 src refspec [branchname] does not match any 뜨면 커밋을 안 한 상태에서 push해서 뜨는 에러에요. 만약에 이 에러 뜨면 아무 파일 하나 생성한 다음에 커밋하고 push 해주세요!
